- name: Установка Nginx
  become: yes
  apt:
    name: nginx
    state: present

- name: Копирование конфигурационного файла
  become: yes
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/default
    owner: root
    group: root
    mode: '0644'

- name: Перезапуск Nginx
  become: yes
  service:
    name: nginx
    state: restarted
