- name: Установка Nginx
  become: yes
  apt:
    name: nginx
    state: present

- name: Создание индексной страницы
  become: yes
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: Перезапуск Nginx
  become: yes
  service:
    name: nginx
    state: restarted
